[package]
name = "vakya"
description = "A modern, powerful rust http library"
repository = "https://github.com/karmaio-rs/vakya"
readme = "README.md"
authors = ["Tarak Sharma <tarak@taraksharma.com>"]
license = "MIT OR Apache-2.0"
exclude = ["AGENTS.md"]

version = "0.1.0"

categories = ["asynchronous", "network-programming", "web-programming"]
keywords = ["async", "http", "karmaio"]

rust-version = "1.95"
edition = "2024"

[features]
default = []
http1 = ["dep:httparse"]
client = ["http1"]
server = ["http1", "dep:httpdate"]
tls = ["karmaio/tls-rustls"]
tracing = ["dep:tracing"]
full = ["client", "server", "tls", "tracing"]

[dependencies]
bytes = "1"
http = "1.5.0"
karmaio = { version = "0.1.0", default-features = false, features = ["bytes", "net"] }
httparse = { version = "1", optional = true }
httpdate = { version = "1", optional = true }
tracing = { version = "0.1", default-features = false, features = ["std"], optional = true }

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "server"
required-features = ["server"]

[[example]]
name = "streaming_echo"
required-features = ["server"]

[[example]]
name = "client"
required-features = ["client"]

[[example]]
name = "informational"
required-features = ["server"]

[[example]]
name = "upgrade"
required-features = ["server"]
